### PR TITLE
KIP-6 Disable distributed front-ends

### PR DESCRIPTION
**Pull request by arthurka-o**
https://www.notion.so/kumos/KIP-6-Disable-distributed-front-ends-04b277efa0184b7c9c6e8dea49c4c915

### CODE REVIEW

**Review by asimpk — APPROVED** [review]
hi @arthurka-o , all the frontend changes looks fine.

**Review by marceljay — COMMENTED** [review]
I'm seeing the latest commits have neat commit bodies, that is great. 
However, the first commit introduces significant changes to a smart contract files. A commit headline "no front-end" is a bit misleading and would be shown in the overall commit history of this repository.

Therefore I suggest renaming the commit and adding a body explaining the **Why** of these changes.

Example (with semantic commits):

```
feat(sol): removed front-end registration

The changes remove functionalities from the contracts that have been used to distribute
rewards to multiple frontends operators. Since the business model for front-end operation
in Kumo is different, we do want to financially incentivize front-end reward share.
```

**Review by marceljay — CHANGES_REQUESTED** [review]
Since this has work-in-progress and shouldn't be merged as it, I submit "request changes".

**Comment by arthurka-o** [comment]
Closing this PR in favor of #394 merging from the fork.

**Pull request closed without merging**
