### PR TITLE
Fix bump ts version

### PR DESCRIPTION
**Pull request by jameschain**

### CODE REVIEW

**Comment by jameschain** [comment]
@udosson merged into one commit.

**Review by wollooo — APPROVED** [review]
LGTM

**Comment by jameschain** [comment]
after ts version upgrade, https://github.com/kumodao/kumo-protocol/blob/dfd4e368f6a1cf552d6cffef14030f623784ab52/packages/lib-ethers/src/ObservableEthersKumo.ts#L58
some weird type issues like above line happened - saying `address` doesn't exist in type `DefaultPool` though `DefaultPool` extends `BaseContract` that has address field. resolved by `any` type for now.

**Comment by asimpk** [comment]
> after ts version upgrade,
> 
> https://github.com/kumodao/kumo-protocol/blob/dfd4e368f6a1cf552d6cffef14030f623784ab52/packages/lib-ethers/src/ObservableEthersKumo.ts#L58
> 
> 
> some weird type issues like above line happened - saying `address` doesn't exist in type `DefaultPool` though `DefaultPool` extends `BaseContract` that has address field. resolved by `any` type for now.

hi @jameschain, could you please remove `any`, most of the time any makes typescript useless

**Comment by udosson** [comment]
@jameschain - could you look up the change that leads to the issues? I'm with @asimpk . We should avoid using `any` as it makes typescript to javascript

**Pull request closed without merging**
