### PR TITLE
Add Husky, Solhint and lint-staged

### PR DESCRIPTION
**Pull request by arthurka-o**

### CODE REVIEW

**Comment by marceljay** [comment]
Any reason why this is still in Draft, would improve things significantly, as mentioned here: https://github.com/kumodao/kumo-protocol/pull/358#discussion_r1267327367

**Comment by marceljay** [comment]
> @marceljay I wrote this in a spare time between two important tasks. Couldn't get something to work (don't remember what exactly now), and had to pause it until I have more time.

Could you explain what exactly did not work? I can try taking this over.
Imho, it's vastly important to add this to the codebase sooner than later.

**Comment by arthurka-o** [comment]
> > @marceljay I wrote this in a spare time between two important tasks. Couldn't get something to work (don't remember what exactly now), and had to pause it until I have more time.
> 
> Could you explain what exactly did not work? I can try taking this over. Imho, it's vastly important to add this to the codebase sooner than later.

I don't exactly remember what was wrong. I think it would be easier to make it from the ground up, looking at this PR as an example.

**Comment by marceljay** [comment]
I'm closing this in favor of #372 but we should keep in mind to add Solhint/Solidity Prettier to the repo.

**Comment by marceljay** [comment]
I'm closing this in favor of https://github.com/kumodao/kumo-protocol/issues/372 but we should keep in mind to add Solhint/Solidity Prettier to the repo.

**Pull request closed without merging**
