### PR TITLE
reqquired packages upgraded and misc issues fixed

### PR DESCRIPTION
**Pull request by asimpk**

### CODE REVIEW

**Comment by udosson** [comment]
@asimpk - thanks for your PR. Would it make sense to merge to the `main` branch and then synch `front-end` with `main`? This could prevent some merge conflicts later

**Comment by udosson** [comment]
@asimpk could you change the base branch to `kumodao:main`, please?

**Comment by udosson** [comment]
@asimpk could you please make a fresh PR with the most recent changes from `main`? Your PR counts 96 commits but only 1 commit would be needed.

**Comment by asimpk** [comment]
> @asimpk could you please make a fresh PR with the most recent changes from `main`? Your PR counts 96 commits but only 1 commit would be needed.

@udosson  It's showing that branch is updated with `main` and I commented on a issue please check 
https://github.com/kumodao/borrowprot/issues/118

**Comment by udosson** [comment]
image
I recommend following these steps:
https://github.com/kumodao/borrowprot/pull/125#issuecomment-1130089312

**Comment by udosson** [comment]
@asimpk - is this PR still active?

**Comment by udosson** [comment]
> @asimpk - is this PR still active?

@asimpk?

**Pull request closed without merging**
